name: calculator_converter
description: "Calculator and Converter is a comprehensive application designed to provide users with both basic and advanced arithmetic functionalities, as well as a variety of conversion tools. This app aims to simplify everyday calculations and conversions, making it a handy tool for students, professionals, and anyone in need of quick mathematical assistance."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter    
    # provider: ^6.0.0
  # bottom_drawer: ^0.0.5
  # google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  image_path: 'assets/logo/c.png'

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/logo/
  
  fonts:
    - family: Trajan Pro
      fonts:
        - asset: assets/fonts/trajan-pro/TrajanPro-Regular.ttf
        - asset: assets/fonts/trajan-pro/Trajanpro-Bold.otf
          weight: 700

